2021-12-21 14:43:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:43:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:43:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:43:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:43:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:44:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:44:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:45:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:45:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:45:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:46:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:52:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:52:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 14:56:13 database: wrong user or password; user: "SA"
org.h2.message.DbException: Nombre de usuario รณ password incorrecto
Wrong user name or password [28000-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Engine.openSession(Engine.java:131)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:309)
	at org.h2.util.JdbcUtils.getConnection(JdbcUtils.java:289)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:785)
	at org.h2.server.web.WebApp.login(WebApp.java:1008)
	at org.h2.server.web.WebApp.process(WebApp.java:223)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:173)
	at org.h2.server.web.WebServlet.doGet(WebServlet.java:129)
	at org.h2.server.web.WebServlet.doPost(WebServlet.java:166)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:219)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:213)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1722)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLInvalidAuthorizationSpecException: Nombre de usuario รณ password incorrecto
Wrong user name or password [28000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:461)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 93 more
2021-12-21 14:58:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 15:01:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 15:01:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
select usuario0_.id as id1_9_, usuario0_.apellido as apellido2_9_, usuario0_.celular as celular3_9_, usuario0_.email as email4_9_, usuario0_.esta_activo as esta_act5_9_, usuario0_.fecha_de_registro as fecha_de6_9_, usuario0_.nombre as nombre7_9_, usuario0_.password as password8_9_, usuario0_.tiempo_registrado as tiempo_r9_9_ from usuarios usuario0_ where usuario0_.email=? [42102-200]
2021-12-21 15:02:10 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "SELECT * FROM INFORMATION_SCHEMA.CATALOGS INFORMATION_SCHEMA.[*]COLUMNS"
Syntax error in SQL statement "SELECT * FROM INFORMATION_SCHEMA.CATALOGS INFORMATION_SCHEMA.[*]COLUMNS"; SQL statement:
SELECT * FROM INFORMATION_SCHEMA.CATALOGS INFORMATION_SCHEMA.COLUMNS [42000-200]
2021-12-21 15:05:52 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/spring/workspace/pasteblock-pd/pasteblockdb.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/spring/workspace/pasteblock-pd/pasteblockdb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/spring/workspace/pasteblock-pd/pasteblockdb.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/spring/workspace/pasteblock-pd/pasteblockdb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/spring/workspace/pasteblock-pd/pasteblockdb.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1297)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2021-12-21 15:06:34 database: flush
org.h2.message.DbException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/spring/workspace/pasteblock-pd/pasteblockdb.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/spring/workspace/pasteblock-pd/pasteblockdb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:93)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:2877)
	at org.h2.mvstore.MVStore.panic(MVStore.java:481)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:402)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
	at org.h2.engine.Database.getPageStore(Database.java:2659)
	at org.h2.engine.Database.open(Database.java:675)
	at org.h2.engine.Database.openDatabase(Database.java:307)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: Error General : "java.lang.IllegalStateException: The file is locked: nio:C:/spring/workspace/pasteblock-pd/pasteblockdb.mv.db [1.4.200/7]"
General error: "java.lang.IllegalStateException: The file is locked: nio:C:/spring/workspace/pasteblock-pd/pasteblockdb.mv.db [1.4.200/7]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 33 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/spring/workspace/pasteblock-pd/pasteblockdb.mv.db [1.4.200/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
	at org.h2.mvstore.FileStore.open(FileStore.java:166)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:381)
	... 27 more
Caused by: java.nio.channels.OverlappingFileLockException
	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
	at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1297)
	at org.h2.store.fs.FileNio.tryLock(FilePathNio.java:121)
	at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1191)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	... 28 more
2021-12-21 15:07:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "USUARIOS" no encontrada
Table "USUARIOS" not found; SQL statement:
insert into usuarios (id, apellido, celular, email, esta_activo, fecha_de_registro, nombre, password, tiempo_registrado) values (null, ?, ?, ?, ?, ?, ?, ?, ?) [42102-200]
2021-12-21 15:08:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "DISTRITOS" no encontrada
Table "DISTRITOS" not found; SQL statement:
select distrito0_.id as id1_6_, distrito0_.nombre as nombre2_6_ from distritos distrito0_ [42102-200]
2021-12-21 15:08:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "DISTRITOS" no encontrada
Table "DISTRITOS" not found; SQL statement:
select distrito0_.id as id1_6_, distrito0_.nombre as nombre2_6_ from distritos distrito0_ [42102-200]
2021-12-21 15:08:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "DISTRITOS" no encontrada
Table "DISTRITOS" not found; SQL statement:
select distrito0_.id as id1_6_, distrito0_.nombre as nombre2_6_ from distritos distrito0_ [42102-200]
2021-12-21 15:08:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "CLIENTES" no encontrada
Table "CLIENTES" not found; SQL statement:
select cliente0_.id as id1_4_, cliente0_.direccion as direccio2_4_, cliente0_.distrito_id as distrito3_4_, cliente0_.numero_servicios_contratados as numero_s4_4_, cliente0_.reputacion as reputaci5_4_, cliente0_.usuario_id as usuario_6_4_ from clientes cliente0_ limit ? [42102-200]
2021-12-21 15:12:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "CLIENTES" no encontrada
Table "CLIENTES" not found; SQL statement:
select cliente0_.id as id1_4_, cliente0_.direccion as direccio2_4_, cliente0_.distrito_id as distrito3_4_, cliente0_.numero_servicios_contratados as numero_s4_4_, cliente0_.reputacion as reputaci5_4_, cliente0_.usuario_id as usuario_6_4_ from clientes cliente0_ limit ? [42102-200]
2021-12-21 15:14:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "CLIENTES" no encontrada
Table "CLIENTES" not found; SQL statement:
select cliente0_.id as id1_4_, cliente0_.direccion as direccio2_4_, cliente0_.distrito_id as distrito3_4_, cliente0_.numero_servicios_contratados as numero_s4_4_, cliente0_.reputacion as reputaci5_4_, cliente0_.usuario_id as usuario_6_4_ from clientes cliente0_ limit ? offset ? [42102-200]
2021-12-21 15:15:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "CLIENTES" no encontrada
Table "CLIENTES" not found; SQL statement:
select cliente0_.id as id1_4_, cliente0_.direccion as direccio2_4_, cliente0_.distrito_id as distrito3_4_, cliente0_.numero_servicios_contratados as numero_s4_4_, cliente0_.reputacion as reputaci5_4_, cliente0_.usuario_id as usuario_6_4_ from clientes cliente0_ limit ? offset ? [42102-200]
2021-12-21 15:16:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "AUTHORITY[*]"; se esperaba "ALTER, ANALYZE"
Syntax error in SQL statement "AUTHORITY[*]"; expected "ALTER, ANALYZE"; SQL statement:
AUTHORITY [42001-200]
2021-12-21 15:17:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "CLIENTES" no encontrada
Table "CLIENTES" not found; SQL statement:
select cliente0_.id as id1_4_, cliente0_.direccion as direccio2_4_, cliente0_.distrito_id as distrito3_4_, cliente0_.numero_servicios_contratados as numero_s4_4_, cliente0_.reputacion as reputaci5_4_, cliente0_.usuario_id as usuario_6_4_ from clientes cliente0_ limit ? offset ? [42102-200]
2021-12-21 15:17:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Tabla "CLIENTES" no encontrada
Table "CLIENTES" not found; SQL statement:
select cliente0_.id as id1_4_, cliente0_.direccion as direccio2_4_, cliente0_.distrito_id as distrito3_4_, cliente0_.numero_servicios_contratados as numero_s4_4_, cliente0_.reputacion as reputaci5_4_, cliente0_.usuario_id as usuario_6_4_ from clientes cliente0_ limit ? [42102-200]
